### ISSUE TITLE
Wyśrodkowanie menu

### ISSUE THREAD

**Issue by aduh** [inventea/we_universal#21]
Jak wyśrodkować "główne" menu (inventea-user-menu).
tutaj: http://admyt.pl/forum
główne menu: Aktualnosci Board Index ...

**Comment by jaroslw** [comment]
Rozwiązanie dla najnowszej wersji z repozytorium:

1. Otwórz `navbar_header.html`, znajdź:
```
	<div class="inventea-forum-menu">
		<ul class="inventea-menu" role="menubar">
```
Zamień na:
```
	<div class="inventea-forum-menu" style="left: 50%;">
		<ul class="inventea-menu" role="menubar" style="position: relative; left: -50%;">
```
Identyczne zmiany można zastosować dla `.inventea-posts-menu`.
