### ISSUE TITLE
Buttons on Viewtopic.php

### ISSUE THREAD

**Issue by Stanzilla** [inventea/we_universal#23]
My mistake or actual theme bug? http://i.imgur.com/8ZSWkpu.png

**Comment by jaroslw** [comment]
Stable version 2.3.0 for phpBB 3.0 or development for phpBB 3.1?

**Comment by Stanzilla** [comment]
Oh, sorry. it's git develop on 3.1.2

**Comment by jaroslw** [comment]
No problem. It's still a bit confusing because I haven't changed buttons in develop yet. Did you make any changes in code? This is how it looks currently: https://inventea.com/phpbb/3.1/viewtopic.php?f=2&t=1

**Comment by Stanzilla** [comment]
Okay, I had some files from the old theme in the folders, sorry!
