### ISSUE TITLE
[PHPBB 3.1] To top scroller

### ISSUE THREAD

**Issue by Stanzilla** [inventea/we_universal#26]
The to top scroller button currently does not work. I tested it in my own and in your demo forum.

**Comment by jaroslw** [comment]
Please give me more details. Did you mean sticky navigation bar or "Top" anchors (for example in posts)? By sticky navigation bar I mean:

![sticky_nav](https://cloud.githubusercontent.com/assets/251475/5806086/d1ef8b94-a015-11e4-85b5-db813960fc8e.png)

**Comment by Stanzilla** [comment]
The top anchor in posts
![2015-01-19_20-24-28](https://cloud.githubusercontent.com/assets/75278/5806400/3afefc3e-a019-11e4-8048-27a088ae744e.png)

**Comment by jaroslw** [comment]
Fixed. I switched back to #wrap id used in prosilver since some extensions may also use it.
