### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by ltjones** [inventea/we_universal#27]
Can you make the image clickable, and make it optional to have the board text. As if I want to add a forum image I have to remove the forum name, so it shows up blank in the tab. Otherwise the image has the board name over it in the header.

**Comment by jaroslw** [comment]
Unfortunately I cannot make two versions at once. Current version is more popular. However you don't need to remove your forum name in forum settings. From `overall_header.html` remove:
```
<div class="inventea-sitename">
				<h1><a href="<!-- IF U_SITE_HOME -->{U_SITE_HOME}<!-- ELSE -->{U_INDEX}<!-- ENDIF -->" title="<!-- IF U_SITE_HOME -->{L_SITE_HOME}<!-- ELSE -->{L_INDEX}<!-- ENDIF -->">{SITENAME}</a></h1>
				<span>{SITE_DESCRIPTION}</span>
			</div>
```
To make image clickable, in the same file find `<div class="inventea-dashboard">` and AFTER add:
```
<a href="YOUR_SITE_URL" style="position: absolute; width: 100%; height: 100%;"></a>
```
