### ISSUE TITLE
PM Graphics Bugs

### ISSUE THREAD

**Issue by MexicanSlideshowWarrior** [inventea/we_universal#28]
See Images.

[drop down options box](http://i.imgur.com/Ya4bG6G.png) and [streching quote off page](http://i.imgur.com/NcXmZai.png)

Happened on a 1080p screen. If you need any more info, I would be happy to provide it.

**Comment by jaroslw** [comment]
Thanks, I'll check that.

**Comment by jaroslw** [comment]
Invisible dropdown is fixed. I cannot reproduce the problem with stretched quote. If you still have it, please open a new ticket with more details.
