### ISSUE TITLE
[Discussion] Minifiy CSS/JS for releases?

### ISSUE THREAD

**Issue by Stanzilla** [inventea/we_universal#39]
I just looked at some speed tests for my site and I noticed that the we_universal files are not minified, would that be something you guys would do for releases only or is it not worth it?

**Comment by jaroslw** [comment]
I was considering this, especially for 2.3.x release which contains big single `we_universal.css` file. Unfortunately minified version could be a problem for people using Administration Control Panel editor and next step to even more questions like "Why I don't see any changes?".

we_unviersal 2.4.0 inherits base JS/CSS from prosilver so impact won't be that noticeable. However files from our `theme/` directory still can be minified. I won't do it in official release and rather would provide some kind of tool/script to automate this for people how are interested in.

Almost a year ago I wrote very simple Python script that grabs CSS files listed in stylesheet.css and outputs it as single stylesheet.min.css: https://gist.github.com/jaroslw/11282495

**Comment by jaroslw** [comment]
I would like to come back to this discussion. There are so many nice ways to automate this that I no longer consider using custom scripts. With next major release I will include gulp.js build script. That means we can easily concatenate and minify CSS/JS sources.

I'm also considering second enhancement - using some PostCSS plugins e.g. variables (for colour scheme) and auto vendor prefixes.

**Comment by Stanzilla** [comment]
:+1:

**Comment by Stanzilla** [comment]
Any news here? Would love to get those improvements :)

**Comment by jpustula** [comment]
I'll check this evening how much work is required to update the style for phpBB 3.2 RC1. Probably I will release updated style package as first and that CSS preprocessor changes will be in next major release.

**Comment by Stanzilla** [comment]
You mean you will release a 3.1.9 version with CSS changes or that the CSS changes will only be in the 3.2.0 version?

**Comment by jpustula** [comment]
CSS changes will be only for phpBB 3.2.
