### ISSUE TITLE
Bad view on mobile Style version: 2.4.3

### ISSUE THREAD

**Issue by PeopleInside** [inventea/we_universal#51]
Style version: 2.4.3
Tested on phpBB version: 3.1.6

Hi, IF I see this page:
https://www.peopleinside.it/forum/viewtopic.php?f=3&t=29
on the mobile the image and also text go over the forum.

For see the issue just try to resize slowly the browser window size and you will see an issue in responsive.

Can be this fixed in some way?
Thanks.
Also from an IPAD the look of this page are wrong.

The screen above is from the PC with small window resized.
![1](https://cloud.githubusercontent.com/assets/5006150/11913940/8edc6a78-a674-11e5-8aef-536f99fa8660.png)

**Comment by PeopleInside** [comment]
Browser: Firefox

**Comment by PeopleInside** [comment]
Aw new theme update but this bug is not yet resolved, hope will be in the next version. Also we universal 2.4.4 are affected.

**Comment by PeopleInside** [comment]
Hope the next version can fix this BUG.
This BUG affect my forum where there are some topic with images or video.
Thank you for this great theme!

**Comment by jaroslw** [comment]
Please check latest development version and confirm if it resolved your problem. I've made this changes:
https://github.com/inventea/we_universal/commit/977a6abfd5b40d8f052f73a27737e207224036dc

This also fixes broken posts image scaling  in Firefox.

**Comment by PeopleInside** [comment]
Hi,
thank you @jaroslw  
I AM trying to understand how I can download that file.

**Comment by PeopleInside** [comment]
@jaroslw I never find a way to download the edited file... tried to download all theme again but seems be not fixed in the downloaded... so I copy all your file edit and pasted is my content.css by replacing all, and **works**.

Thank you for this fix!
