### ISSUE TITLE
Staff link still visible also if there are no permission

### ISSUE THREAD

**Issue by PeopleInside** [inventea/we_universal#54]
Hi,
I see if I allow guest to see user list the link members and staff is showed by the template in the menu, if I disable the permission to not registered to see user member list only member link are hidden, staff member still be showed.

Is a bug?

Will be nice have option in the theme for decide if show that two link or not.

**Comment by jaroslw** [comment]
Hi! I believe that the same behaviour is in prosilver. The Team link is displayed on `<!-- IF U_TEAM -->` condition while Memberlist has its own `<!-- IF S_DISPLAY_MEMBERLIST -->`.

For logged in users `U_TEAM` checks user permission if viewing profile is allowed:
https://github.com/phpbb/phpbb/blob/release-3.1.6/phpBB/includes/functions.php#L5171

I will stick with standard but you can easily change that line:
https://github.com/inventea/we_universal/blob/master/we_universal/template/navbar_header.html#L27

to:
```
<!-- IF U_TEAM and S_DISPLAY_MEMBERLIST --><li><a href="{U_TEAM}" role="menuitem">{L_THE_TEAM}</a></li><!-- ENDIF -->
```

**Comment by PeopleInside** [comment]
Thank you for the reply.
