### ISSUE TITLE
phpbb 3.2 compat?

### ISSUE THREAD

**Issue by Stanzilla** [inventea/we_universal#62]
I was thinking about upgrading my forums to the RC1 of 3.2, how well is we_universal working with it atm?

**Comment by jpustula** [comment]
It may run, however phpBB 3.2 has new template changes and some features may not work. Was RC1 officially announced?

**Comment by Stanzilla** [comment]
Don't think so, https://download.phpbb.com/pub/release/3.2/unstable/3.2.0-RC1/ has been there since May, no news post yet though and no tag on the repo https://github.com/phpbb/phpbb/tags

**Comment by jpustula** [comment]
That's way I missed it. I'll check this evening if it works with phpBB 3.2 but I think it won't be production ready without updating.

**Comment by jpustula** [comment]
For now I'm not able to install phpBB 3.2 RC1. It constantly redirects to Introduction page. I see a lot of changes in templates. Running we_universal will require more work than I expected for now.

I think the roadmap will be:
1. Release minor update to make we_universal compatible with phpBB 3.2 (maybe with next RC).
2. Release major version with new features (such as CSS changes from #39).

That approach will allow to smooth transition between we_universal versions. With major release I also would like to enhance extensions support (mostly related to forumlist and topiclist).

**Comment by Stanzilla** [comment]
Sounds good :) Guess I could just minify the css myself for the time being

**Comment by jpustula** [comment]
I think it can be easily automated using Gulp with some plugins such as:
- gulp-import-css (https://www.npmjs.com/package/gulp-import-css)
- gulp-clean-css (https://github.com/scniro/gulp-clean-css)

**Comment by Stanzilla** [comment]
There we go https://www.phpbb.com/community/viewtopic.php?f=14&t=2377556

**Comment by Stanzilla** [comment]
@jaroslw did you have time to take a look yet?

**Comment by jimsefton** [comment]
I really would like to use this theme in 3.2... any news if it is still in development?

**Comment by Stanzilla** [comment]
@jaroslw any news here?

**Comment by ernestpasnik** [comment]
I also would like to use this style, phpBB 3.2 Rhea will be made available in a few days.

**Comment by ghost** [comment]
@jaroslw, any news on this being updated to be compatible with PHPBB 3.2.0?

**Comment by dantgal** [comment]
@jaroslw - do you plan to update it to 3.2.0 ?

**Comment by Galixte** [comment]
@jaroslw Hi Jarosław, any news about 3.2.x version for We universal ? Regards.

**Comment by PeopleInside** [comment]
https://www.phpbb.com/community/viewtopic.php?f=596&t=2404676
