### ISSUE TITLE
Multilanguage Forum: Show option to select language

### ISSUE THREAD

**Issue by PeopleInside** [inventea/we_universal#63]
Hi,
I Am using your theme but multilanguage drop down menu is visible only in the registration page.
Can you add a way to let user choose language also when is viewing the forum and are not logged in?

**Comment by jpustula** [comment]
Sorry, I don't add features that are not available in standard phpBB or prosilver. 

If you are using phpBB 3.0, there are two modifications available:
https://www.phpbb.com/customise/db/mod/language_selection_mod/
https://www.phpbb.com/customise/db/mod/mssti_quick_language

For phpBB 3.1 I've found this:
https://github.com/alg5/quicklanguage

Unfortunately I haven't used any of them and can't tell if they work with latest phpBB versions.

**Comment by PeopleInside** [comment]
Thank you, I will try to find how to do in the phpbb forum as I AM using not an old version of phpbb :-)
